### ISSUE TITLE
[PREGUNTA] Middleware

### ISSUE THREAD

**Issue by LcsGrz** [OnigiriFest/recipes-api#6]
https://github.com/OnigiriFest/recipes-api/blob/7c1922a94bf8d3ddc4d0ce4ceb319207da0b6d13/src/resolvers/user.ts#L11

Aca con esta validacion me uqeda la duda si es redundante, si vos agregas la middleware, no se encargaria ella de checkear esto?

**Comment by facundopanizza** [comment]
Sisi, estaba repitiendo codigo y cree el middleware pero se me escapo este caso!
